#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# git add -A

case `uname` in
  *CYGWIN*|*MINGW*|*MSYS*)
    npx.cmd lint-staged # bug on Windows/Github Desktop: add `.cmd` extension fixes it
  ;;
  *)
    npx lint-staged
  ;;
esac
